on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 1.2.335

      - name: Install Quarto Extensions
        run: |
          quarto install --no-prompt extension jmbuhr/quarto-qrcode
          quarto install --no-prompt extension grantmcdermott/quarto-revealjs-clean

      - name: Install Python Dependencies
        run: |
          pip3 install jupyter nbformat

      - name: Render Slides
        uses: quarto-dev/quarto-actions/render@v2.1.2
        with:
          to: website

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2.1.2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
